<?php

namespace api\controllers;

use yii\rest\ActiveController;
use yii\web\Response;

class ApiController extends ActiveController
{

    public $token_key = false;
    private $token_keys = array();

    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        // add CORS filter
        $behaviors['corsFilter'] = [
            'class' => \yii\filters\Cors::class,
        ];
        return $behaviors;
    }

    public function actions()
    {
        return [];
    }

    public function response($status, $message, $data = null, $errors = null, $responsStatusCode = 200)
    {
        \Yii::$app->response->statusCode = $responsStatusCode;
        $response = [
            'status' => $status,
            'message' => $message
        ];
        if ($data) $response['data'] = $data;
        if ($errors) $response['errors'] = $errors;
        return $response;
    }

    public function load($model, $data)
    {
        return $model->load($data, '');
    }

}