<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace api\models;

use \Yii;

/**
 * This is the base-model class for table "ip_students_info".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $last_name
 * @property string $first_name
 * @property string $middle_name
 * @property string $passport_seria
 * @property integer $passport_number
 * @property integer $passport_pin
 * @property string $passport_given_date
 * @property string $passport_issued_date
 * @property string $passport_given_by
 * @property string $birthday
 * @property string $phone
 * @property string $address
 * @property integer $gender
 * @property integer $region_id
 * @property integer $district_id
 * @property integer $diplom_number
 * @property string $diplom_seria
 * @property string $diplom_date
 * @property string $course
 * @property string $faculty
 * @property integer $status
 *
 * @property \common\models\User $user
 * @property string $aliasModel
 */
class IpStudentsInfo extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ip_students_info';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

            [['user_id', 'passport_number', 'passport_pin', 'gender', 'region_id', 'district_id', 'diplom_number', 'status'], 'integer'],
            [['passport_given_date', 'passport_issued_date', 'birthday', 'diplom_date'], 'safe'],
            [['last_name', 'first_name', 'middle_name', 'passport_given_by'], 'string', 'max' => 55],
            [['passport_seria'], 'string', 'max' => 2],
            [['phone', 'address', 'diplom_seria', 'course', 'faculty'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('ui', 'ID'),
            'user_id' => Yii::t('ui', 'User ID'),
            'last_name' => Yii::t('ui', 'Last Name'),
            'first_name' => Yii::t('ui', 'First Name'),
            'middle_name' => Yii::t('ui', 'Middle Name'),
            'passport_seria' => Yii::t('ui', 'Passport Seria'),
            'passport_number' => Yii::t('ui', 'Passport Number'),
            'passport_pin' => Yii::t('ui', 'Passport Pin'),
            'passport_given_date' => Yii::t('ui', 'Passport Given Date'),
            'passport_issued_date' => Yii::t('ui', 'Passport Issued Date'),
            'passport_given_by' => Yii::t('ui', 'Passport Given By'),
            'birthday' => Yii::t('ui', 'Birthday'),
            'phone' => Yii::t('ui', 'Phone'),
            'address' => Yii::t('ui', 'Address'),
            'gender' => Yii::t('ui', 'Gender'),
            'region_id' => Yii::t('ui', 'Region ID'),
            'district_id' => Yii::t('ui', 'District ID'),
            'diplom_number' => Yii::t('ui', 'Diplom Number'),
            'diplom_seria' => Yii::t('ui', 'Diplom Seria'),
            'diplom_date' => Yii::t('ui', 'Diplom Date'),
            'course' => Yii::t('ui', 'Course'),
            'faculty' => Yii::t('ui', 'Faculty'),
            'status' => Yii::t('ui', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }



    /**
     * @inheritdoc
     * @return \common\models\query\IpStudentsInfoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\IpStudentsInfoQuery(get_called_class());
    }

    public function fields()
    {
        return  [
            'id',
           // 'user_id' ,
            'last_name',
            'first_name' ,
            'middle_name' ,
            'passport_seria' ,
            'passport_number',
            'passport_pin' ,
            'passport_given_date',
            'passport_issued_date',
            'passport_given_by',
            'birthday',
            'phone',
            'address',
            'gender',
            'region_id',
            'district_id',
            'diplom_number' ,
            'diplom_seria',
            'diplom_date',
            'course',
            'faculty',
            'status'
        ];
    }


    public function extraFields()
    {
        return  [

        ];

    }

    public static function createItem($model, $post)
    {
        $transaction = Yii::$app->db->beginTransaction();
        $errors = [];

        if (!($model->validate())) {
            $errors[] = $model->errors;
        }
        if ($model->save()) {
            $transaction->commit();
            return true;
        } else {
            $transaction->rollBack();
            return simplify_errors($errors);
        }
    }

}
